install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
devtools::install_github("statsmaths/coreNLP")
coreNLP::downloadCoreNLP()